### ISSUE TITLE
Check for multiple show() calls and/or provide isShown() method

### ISSUE THREAD

**Issue by makks129** [jesualex/sTooltip#5]
Currently calling `show()` twice throws an exception.
It would be nice to have `if (!isShown()) show()` check or simply to provide an `isShown()` method so we could perform this check manually. (Same logic with close)

Thanks, Jesus, this library is awesome!

**Comment by jesualex** [comment]
Hi again @makks129 

Thank you for reporting that issue, it has already been corrected, i will upload a version 1.4 and it will be ok.

In that version i will also add the function that you are mentioning "isShown", but also something similar already existed to know in what state the Tooltip is, that is "displayListener".

Finally, since in the email you wrote to me you mentioned the subject of the images, would you collaborate with me by taking a few screens and sending them to the email? So for this next version we also improve the readme a bit :)
